### ISSUE TITLE
Kotlin Multiplatform Libraries not in plugin.yml

### ISSUE THREAD

**Issue by NyCodeGHG** [NyCodeGHG/gradle-spigot-dependency-loader#4] opened 2022-01-29 23:26 UTC
/cc @DerTev

**Comment by DRSchlaubi** [comment] 2022-01-30 00:35
I assume this only happens if you use the MPP and not the `-jvm  dependency.

My guess is the mpp dependency gets included, but aether cannot handle that?

**Comment by DRSchlaubi** [comment] 2022-01-30 01:51
Okay, the issue is, that the MPP module doesn't have any module artifacts, should be fixed in the next version

**Closed as completed** 2022-01-30 02:04 UTC
Labels: bug
